### ISSUE TITLE
a script for uninstall

### ISSUE THREAD

**Issue by gl-web** [lixuy/LTSB-Add-MicrosoftStore#1]
Hello,

Would it be possible to create a script to uninstall Store Apps ?

PS : Sorry for my bad english, i am French...

Thanks

**Comment by kkkgo** [comment]
http://www.chuyu.me
You can use this tool to uninstall Store Apps

**Comment by kkkgo** [comment]
try:
create uninstall.cmd:
>PowerShell "Get-AppxPackage Microsoft.* | Remove-AppxPackage" 2>nul
for /f "delims=" %%i in ('dir /ad/b "%ProgramFiles%\WindowsApps\*Microsoft.**neutral*" 2^>nul') do (
    "%windir%\system32\Dism.exe" /online /Remove-ProvisionedAppxPackage /PackageName:"%%~i"
)

run as admin.
